Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = np.array ([[1,3,9],[3,-2,6],[9,4,1]])
B = np.array ([[1,7,5],[2,4,3]])
C = np.array ([[3,2],[-1,2],[3,5]])
D = np.array ([[5,3,4],[3,2,1],[1,4,9]])
E = A+B
F = 2*A
G = A@c
H = B@C
// A(BC) + (AB)
------------------


[0;36m  File [0;32m"<ipython-input-6-9aa4c1022baa>"[0;36m, line [0;32m9[0m
[0;31m    // A(BC) + (AB)[0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


